### ISSUE TITLE
Ouathlib raises exception for insecure transport on HTTPS

### ISSUE THREAD

**Issue by hypergonial** [jnawk/Quart-Discord#13]
I managed to set up a Quart instance with hypercorn on DigitalOcean's PaaS (App Platform) but for whatever reason, oauthlib refuses any and all callbacks due to "Insecure transport", which is interesting as DO provides SSL and HTTPS out of the box. Do I need additional configuration for hypercorn, this plugin, or anything else?

Thanks for your time.

**Comment by hypergonial** [comment]
Solution: Quart does not seem to support reverse-proxies properly, and fools oauthlib into thinking that the request came through http, triggering the error. So if you're like me, and use Quart with a reverse-proxy, enable insecure transport.

**Comment by veerack** [comment]
getting the same error here, website is proxied with Cloudflare..

**Comment by jnawk** [comment]
> Solution: Quart does not seem to support reverse-proxies properly, and fools oauthlib into thinking that the request came through http, triggering the error. So if you're like me, and use Quart with a reverse-proxy, enable insecure transport.

How can it possibly trust headers in the request promising the request was secure?

**Comment by veerack** [comment]
i actually fixed this just by changing my `redirect_uri` inside the discord developer portal from `https` over to `http`.

looks like setting up the redirect_uri directly as `https` triggers something within cloudflare & nginx and makes it return as `http`
