### ISSUE TITLE
Hello, I need help, I want to calculate the guilds of my bot, how can I do this?

### ISSUE THREAD

**Issue by Taqerun** [jnawk/Quart-Discord#14]
Hello, I need help, I want to calculate the guilds of my bot, how can I do this?

**Comment by jnawk** [comment]
Bot Request docs:
https://quart-discord.readthedocs.io/en/latest/_modules/quart_discord/_http.html#DiscordOAuth2HttpClient.bot_request

Discord docs:
https://discord.com/developers/docs/resources/user#get-current-user-guilds

Discord guild where you may find other users of Flask-Discord and Quart-Discord
https://discord.gg/7CrQEyP

**Comment by SudoSteven** [comment]
You can use the discord-ext-ipc for communicating with your bot.

GitHub: https://github.com/Ext-Creators/discord-ext-ipc
Docs: https://ext-creators.github.io/docs/ipc/
